// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dm": {
            "get": {
                "description": "Получить список кодов маркировки с пагинацией по фильтрам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dm"
                ],
                "summary": "Получение списка кодов маркировки",
                "parameters": [
                    {
                        "type": "string",
                        "name": "aggregate",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "name": "dm",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "gtin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "taskid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.DataMatrixCode"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DataMatrixCode": {
            "type": "object",
            "properties": {
                "aggregate": {
                    "type": "string"
                },
                "crpt_state": {
                    "type": "string",
                    "example": "0"
                },
                "crpt_template_idx": {
                    "type": "integer"
                },
                "dm": {
                    "type": "string"
                },
                "dm_8005": {
                    "type": "string"
                },
                "dm_91": {
                    "type": "string"
                },
                "dm_92": {
                    "type": "string"
                },
                "dm_93": {
                    "type": "string"
                },
                "dm_tail": {
                    "type": "string"
                },
                "emission_date": {
                    "type": "string"
                },
                "emission_document": {
                    "type": "string"
                },
                "gtin": {
                    "type": "string"
                },
                "insert_by": {
                    "type": "string"
                },
                "payment_on_emission": {
                    "type": "boolean"
                },
                "processing_in_document": {
                    "type": "string"
                },
                "scandate": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "0"
                },
                "taskid": {
                    "type": "integer"
                },
                "verification_device": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer"
                },
                "weight": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.4.5",
	Host:             "",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "DMC GO Rest API",
	Description:      "Это Rest API для DMC на базе Go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
